#!/bin/sh -xe

type -p gh > /dev/null || { echo "ERROR: gh tool not found"; exit 1; }
type -p jq > /dev/null || { echo "ERROR: jq tool not found"; exit 1; }

repo="kdave/btrfs-progs"

for id in $(gh run -R "$repo" list -w 'Devel build and tests' -s failure --json databaseId | jq '.[].databaseId'); do
	echo "Delete run $id"
	gh run -R "$repo" delete "$id"
done
