#!/bin/sh
# download, build and install reiserfs library

version=3.6.27
dir=tmp-cached-reiser
stamp="$dir/.last-build-reiser"
here=`pwd`

set -e

if [ -d "$dir" -a -f "$stamp" ]; then
	echo "Using valid cache for $dir, built" `cat "$stamp"`
	cd "$dir"
	cd reiserfsprogs-${version}
	sudo make install
	exit 0
fi

echo "No or stale cache for $dir, rebuilding"
rm -rf "$dir"
mkdir "$dir"
cd "$dir"
wget https://www.kernel.org/pub/linux/kernel/people/jeffm/reiserfsprogs/v${version}/reiserfsprogs-${version}.tar.xz
tar xf reiserfsprogs-${version}.tar.xz
cd reiserfsprogs-${version}
# Compilation fails as loff_t is not defined without the define
export CFLAGS
CFLAGS=-D_GNU_SOURCE
./configure --prefix=/usr
make all
sudo make install
date > "$here/$stamp"
